---
title: "Matt's Christmas List 2024"
author: "Matthew Bray"
format: html
editor: visual
---

# Welcome to Christmas 2024! I hope you are as excited for the season as I am! I've taken the steps necessary to simplify all of your shopping and selection needs! The links below will take you to specific items. Camera related items are product specific and may not work if substituted. All remaining items, feel free to substitute as you wish, you're the giver!!!!

## First, we'll start with Camera stuff. I've been enjoying taking wildlife pictures over the past year and a half in Massachusetts. There are a lot of hidden pockets of life still left! Here are some examples! [November 2024 Eiders, Brant, and Black Ducks](https://mattbray.smugmug.com/October-Waterfowl)

The following are two options for memory cards that work in my camera. It has a slot for both, using the CFExpress Type B card as primary and the SD style card as a backup. The CFExpress cards are really fast, but they also heat up quite a bit when downloading off the cards, so smaller is probably better so there are not multiple thousands of pictures on each card.

[CFExpress Type B 128 GB](https://www.bhphotovideo.com/c/product/1551687-REG/sandisk_sdcfe_128g_ancnn_128gb_extreme_pro_cfexpress.html)

[SDXC 256 GB](https://www.bhphotovideo.com/c/product/1617742-REG/sandisk_sdsdxdk_256g_ancin_256gb_extreme_pro_uhs_ii.html)

## I've been wearing out my wool socks lately, its a lot colder in Massachusetts than NC! [Woolies](https://www.smartwool.com/en-us/wool-apparel-and-socks/everyday-socks/everyday-cozy-snowed-in-sweater-crew-socks/SW002186.html?dwvar_SW002186_size=L&dwvar_SW002186_color=A25) I wear large if the link doesn't work accurately. A different style, perhaps:[Yellow Woolies](https://www.smartwool.com/en-us/wool-apparel-and-socks/everyday-socks/everyday-cozy-digi-tick-crew-socks/SW002505.html?dwvar_SW002505_size=L&dwvar_SW002505_color=100)

## I also go through lot of caffeine on my photo trips! I have to get up early to get to the Cape before sunrise! I looked at Black Dog Coffee and I found a few that look really tasty! [Costa Rica Tarazu](https://blackdogcoffee.net/product/tarrazu-fruta-de-oro/) [Huehuetenango](https://blackdogcoffee.net/product/huehuetenango/).
